import 'dart:convert';

import 'package:dailydiary/apis/model.dart';
import 'package:http/http.dart' as http;

// ignore: camel_case_types
class API_Manager {
  Future<Autogenerated>getNews() async {
    var client = http.Client();
    var newsModel;


      var response = await client.get(Uri.parse('https://recipesapi.herokuapp.com/api/v2/categories'));
        var jsonString = response.body;
        var jsonMap = json.decode(jsonString);

        newsModel = Autogenerated.fromJson(jsonMap);

    return newsModel;
  }
}
